# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f76d9c7059e333a5b3a2e3b9f2ab047b4301fb806fb9b9f7b04d18af752c83939997bd1a7f39d4580de9d0b0c5f960cd46baccb385f60f53fc56c9a86992beda

test:
  secret_key_base: 459f15181f8b0818affe0f175fce78957ab205d879705a62b19272660a1517c321bc7ca74fff921e87debf51eba4972984a43afa97f3534192ce6459825f4b6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
